### ISSUE TITLE
Model versions do not match？frame error

### ISSUE THREAD

**Issue by Kingzerd** [umich-vl/CornerNet#128]
/home/kingzerd/anaconda3/envs/CornerNet/bin/python /home/kingzerd/share/Code/Ubuntu/PycharmProjects/CornerNet-master/train.py CornerNet
loading all datasets...
using 4 threads
loading from cache file: ./cache/coco_stest.pkl
loading annotations into memory...
Done (t=0.36s)
creating index...
index created!
loading from cache file: ./cache/coco_stest.pkl
loading annotations into memory...
Done (t=0.37s)
creating index...
index created!
loading from cache file: ./cache/coco_stest.pkl
loading annotations into memory...
Done (t=0.35s)
creating index...
index created!
loading from cache file: ./cache/coco_stest.pkl
loading annotations into memory...
Done (t=0.37s)
creating index...
index created!
loading from cache file: ./cache/coco_stest.pkl
loading annotations into memory...
Done (t=0.41s)
creating index...
index created!
system config...
{'batch_size': 3,
 'cache_dir': './cache',
 'chunk_sizes': [3],
 'config_dir': './config',
 'data_dir': './data',
 'data_rng': <mtrand.RandomState object at 0x7f41a52a5d80>,
 'dataset': 'MSCOCO',
 'decay_rate': 10,
 'display': 5,
 'learning_rate': 0.00025,
 'max_iter': 500000,
 'nnet_rng': <mtrand.RandomState object at 0x7f41a52a5dc8>,
 'opt_algo': 'adam',
 'prefetch_size': 5,
 'pretrain': None,
 'result_dir': './results',
 'sampling_function': 'kp_detection',
 'snapshot': 5000,
 'snapshot_name': 'CornerNet',
 'stepsize': 450000,
 'test_split': 'testdev',
 'train_split': 'trainval',
 'val_iter': 100,
 'val_split': 'minival',
 'weight_decay': False,
 'weight_decay_rate': 1e-05,
 'weight_decay_type': 'l2'}
db config...
{'ae_threshold': 0.5,
 'border': 128,
 'categories': 12,
 'data_aug': True,
 'gaussian_bump': True,
 'gaussian_iou': 0.3,
 'gaussian_radius': -1,
 'input_size': [511, 511],
 'lighting': True,
 'max_per_image': 100,
 'merge_bbox': False,
 'nms_algorithm': 'exp_soft_nms',
 'nms_kernel': 3,
 'nms_threshold': 0.5,
 'output_sizes': [[128, 128]],
 'rand_color': True,
 'rand_crop': True,
 'rand_pushes': False,
 'rand_samples': False,
 'rand_scale_max': 1.4,
 'rand_scale_min': 0.6,
 'rand_scale_step': 0.1,
 'rand_scales': array([0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3]),
 'special_crop': False,
 'test_scales': [1],
 'top_k': 100,
 'weight_exp': 8}
len of db: 2868
start prefetching data...
shuffling indices...
start prefetching data...
shuffling indices...
start prefetching data...
shuffling indices...
start prefetching data...
shuffling indices...
building model...
module_file: models.CornerNet
start prefetching data...
shuffling indices...
total parameters: 200965308
setting learning rate to: 0.00025
training start...
  0%|                                                | 0/500000 [00:00<?, ?it/s]/

Traceback (most recent call last):
  File "/home/kingzerd/share/Code/Ubuntu/PycharmProjects/CornerNet-master/train.py", line 196, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "/home/kingzerd/share/Code/Ubuntu/PycharmProjects/CornerNet-master/train.py", line 138, in train
    training_loss = nnet.train(**training)
  File "/home/kingzerd/share/Code/Ubuntu/PycharmProjects/CornerNet-master/nnet/py_factory.py", line 83, in train
    loss.backward()
  File "/home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/autograd/function.py", line 77, in apply

    return self._forward_cls.backward(self, *args)
  File "/home/kingzerd/share/Code/Ubuntu/PycharmProjects/CornerNet-master/models/py_utils/_cpools/__init__.py", line 57, in backward
    output = right_pool.backward(input, grad_output)[0]
RuntimeError: Expected object of type Variable but found type CUDAType for argument #0 'result' (checked_cast_variable at /opt/conda/conda-bld/pytorch_1556653099582/work/torch/csrc/autograd/VariableTypeManual.cpp:173)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f41cc008dc5 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch::autograd::VariableType::checked_cast_variable(at::Tensor&, char const*, int) + 0x169 (0x7f41c99be379 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #2: torch::autograd::VariableType::unpack(at::Tensor&, char const*, int) + 0x9 (0x7f41c99be419 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #3: torch::autograd::VariableType::s__th_gt_out(at::Tensor&, at::Tensor const&, at::Tensor const&) const + 0x237 (0x7f41c97edda7 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #4: at::TypeDefault::_th_gt_out(at::Tensor&, at::Tensor const&, at::Tensor const&) const + 0x205 (0x7f41cccc2115 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #5: at::TypeDefault::gt_out(at::Tensor&, at::Tensor const&, at::Tensor const&) const + 0x62 (0x7f41ccca4a72 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #6: torch::autograd::VariableType::gt_out(at::Tensor&, at::Tensor const&, at::Tensor const&) const + 0x340 (0x7f41c988a710 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #7: pool_backward(at::Tensor, at::Tensor) + 0x4fe (0x7f41a4a35fde in /home/kingzerd/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/right_pool.cpython-36m-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x10090 (0x7f41a4a3f090 in /home/kingzerd/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/right_pool.cpython-36m-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x10f6a (0x7f41a4a3ff6a in /home/kingzerd/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/right_pool.cpython-36m-x86_64-linux-gnu.so)
frame #10: _PyCFunction_FastCallDict + 0x154 (0x55e463022b94 in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #11: <unknown function> + 0x19e67c (0x55e4630b267c in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x2fa (0x55e4630d4cba in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #13: PyEval_EvalCodeEx + 0x329 (0x55e4630ad459 in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #14: <unknown function> + 0x19a264 (0x55e4630ae264 in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #15: PyObject_Call + 0x3e (0x55e46302299e in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x1ab0 (0x55e4630d6470 in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #17: <unknown function> + 0x197a94 (0x55e4630aba94 in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #18: _PyFunction_FastCallDict + 0x1bb (0x55e4630ace1b in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #19: _PyObject_FastCallDict + 0x26f (0x55e463022f5f in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #20: _PyObject_Call_Prepend + 0x63 (0x55e463027a03 in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #21: PyObject_Call + 0x3e (0x55e46302299e in /home/kingzerd/anaconda3/envs/CornerNet/bin/python)
frame #22: torch::autograd::PyFunction::apply(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> >&&) + 0x193 (0x7f41fb2903b3 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #23: <unknown function> + 0x307622 (0x7f41c938a622 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #24: torch::autograd::Engine::evaluate_function(torch::autograd::FunctionTask&) + 0x385 (0x7f41c9383745 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #25: torch::autograd::Engine::thread_main(torch::autograd::GraphTask*) + 0xc0 (0x7f41c9385740 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #26: torch::autograd::Engine::thread_init(int) + 0x2b0 (0x7f41c93829e0 in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #27: torch::autograd::python::PythonEngine::thread_init(int) + 0x2a (0x7f41fb28ad1a in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #28: <unknown function> + 0xafc5c (0x7f41ca640c5c in /home/kingzerd/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/lib/../../../../libstdc++.so.6)
frame #29: <unknown function> + 0x76db (0x7f420acaa6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #30: clone + 0x3f (0x7f420a9d388f in /lib/x86_64-linux-gnu/libc.so.6)

Process finished with exit code 1

**Comment by Kingzerd** [comment]
When I train the model using my datasets, I get this problem. But when I test my datasets using the model provided, all things work fine.

**Comment by Kingzerd** [comment]
https://github.com/princeton-vl/CornerNet/issues/104#issuecomment-500271649
It perfectly solves my question!
