### ISSUE TITLE
How can I predict the objects in my own pictures？

### ISSUE THREAD

**Issue by Iric2018** [umich-vl/CornerNet#17]

**Comment by heilaw** [comment]
It seems that the path to the image is not correct as `cv2.imread` would return `None` if the image does not exist.

**Comment by Iric2018** [comment]
I just put my own images into the file testdev2017, so there is no problem to the path of the image.

**Comment by heilaw** [comment]
The code reads the image file names from the COCO JSON files. If you just replace COCO images with yours, our code won’t read your images correctly.

**Comment by Iric2018** [comment]
So If I want to use my own images, i should write all the image names into the COCO JSON files first.

**Comment by heilaw** [comment]
Or you can change the `_load_data` function in `db/coco.py`. You just need to save your image file names to the `_image_ids` variable and just set `_detections` to be an empty list.

**Comment by Iric2018** [comment]
Thanks for your help. Follow your way, the problem is solved。But When I run the train.py as it given in your repo, it doesn't work and errors are shown as follow:
(CornerNet) dc2-user@10-255-0-138:~/CornerNet-master-old$ python train.py CornerNet
loading all datasets...
using 4 threads
loading from cache file: ./cache/coco_trainval2014.pkl
No cache file found...
loading annotations into memory...
Done (t=16.20s)
creating index...
index created!
118287it [01:03, 1875.69it/s]
loading annotations into memory...
Done (t=15.54s)
creating index...
index created!
loading from cache file: ./cache/coco_trainval2014.pkl
loading annotations into memory...
Done (t=14.84s)
creating index...
index created!
loading from cache file: ./cache/coco_trainval2014.pkl
loading annotations into memory...
Done (t=14.26s)
creating index...
index created!
loading from cache file: ./cache/coco_trainval2014.pkl
loading annotations into memory...
Done (t=15.78s)
creating index...
index created!
loading from cache file: ./cache/coco_minival2014.pkl
No cache file found...
loading annotations into memory...
Done (t=0.51s)
creating index...
index created!
5000it [00:02, 1881.11it/s]
loading annotations into memory...
Done (t=0.46s)
creating index...
index created!
system config...
{'batch_size': 100,
 'cache_dir': './cache',
 'chunk_sizes': [4, 5, 5, 5, 5, 5, 5, 5, 5, 5],
 'config_dir': './config',
 'data_dir': './data',
 'data_rng': <mtrand.RandomState object at 0x7f82c7263d80>,
 'dataset': 'MSCOCO',
 'decay_rate': 10,
 'display': 5,
 'learning_rate': 0.00025,
 'max_iter': 500000,
 'nnet_rng': <mtrand.RandomState object at 0x7f82c7263dc8>,
 'opt_algo': 'adam',
 'prefetch_size': 5,
 'pretrain': None,
 'result_dir': './results',
 'sampling_function': 'kp_detection',
 'snapshot': 5000,
 'snapshot_name': 'CornerNet',
 'stepsize': 450000,
 'test_split': 'testdev',
 'train_split': 'trainval',
 'val_iter': 100,
 'val_split': 'minival',
 'weight_decay': False,
 'weight_decay_rate': 1e-05,
 'weight_decay_type': 'l2'}
db config...
{'ae_threshold': 0.5,
 'border': 128,
 'categories': 80,
 'data_aug': True,
 'gaussian_bump': True,
 'gaussian_iou': 0.7,
 'gaussian_radius': -1,
 'input_size': [511, 511],
 'lighting': True,
 'max_per_image': 100,
 'merge_bbox': False,
 'nms_algorithm': 'exp_soft_nms',
 'nms_kernel': 3,
 'nms_threshold': 0.5,
 'output_sizes': [[128, 128]],
 'rand_color': True,
 'rand_crop': True,
 'rand_pushes': False,
 'rand_samples': False,
 'rand_scale_max': 1.4,
 'rand_scale_min': 0.6,
 'rand_scale_step': 0.1,
 'rand_scales': array([0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3]),
 'special_crop': False,
 'test_scales': [1],
 'top_k': 100,
 'weight_exp': 8}
len of db: 118287
start prefetching data...
shuffling indices...
Traceback (most recent call last):
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 96, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-1:
Traceback (most recent call last):
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 46, in prefetch_data
    raise e
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 96, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
start prefetching data...
shuffling indices...
start prefetching data...
shuffling indices...
Traceback (most recent call last):
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 96, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-3:
Traceback (most recent call last):
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 46, in prefetch_data
    raise e
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 96, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 96, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-2:
Traceback (most recent call last):
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 46, in prefetch_data
    raise e
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 96, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
start prefetching data...
shuffling indices...
Traceback (most recent call last):
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 96, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-4:
Traceback (most recent call last):
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 46, in prefetch_data
    raise e
  File "train.py", line 42, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 182, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/dc2-user/CornerNet-master-old/sample/coco.py", line 96, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
building model...
module_file: models.CornerNet
start prefetching data...
shuffling indices...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 50, in pin_memory
    data = data_queue.get()
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/dc2-user/anaconda3/envs/CornerNet/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

total parameters: 201035212
setting learning rate to: 0.00025
training start...
  0%|                                                | 0/500000 [00:00<?, ?it/s]

**Comment by heilaw** [comment]
> File "/home/dc2-user/CornerNet-master-old/sample/utils.py", line 58, in random_crop
image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'

It looks like the code cannot read the training images. You can add `print(image_file)` after line 88 in `sample/coco.py` to check the image path.

**Comment by heilaw** [comment]
If the image path is correct, can you reduce your batch size (fyi, we are using a batch size of 49 on 10 GPUs with 12GB memory each) and see if the code can run first?

**Comment by Iric2018** [comment]
I reduce the batch size to 2， but the memory is still not enough。Could you tell me the minimum configuration of GPU?

**Comment by fanzhaowei** [comment]
@Iric2018 hi,I got the same problem "AttributeError: 'NoneType' object has no attribute 'shape'" when i using the author's trained model to look the results.could you please tell me how to solve it?I have already put the test pictures in testdev2017.thank you!

**Comment by fanzhaowei** [comment]
(CornerNet) b306@cv:~/fanzhaowei/CornerNet-master$ python test.py CornerNet --testiter 500000 --split testing
cfg_file: ./config/CornerNet.json
loading all datasets...
split: testdev
loading from cache file: ./cache/coco_testdev2017.pkl
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
system config...
{'batch_size': 49,
 'cache_dir': './cache',
 'chunk_sizes': [4, 5, 5, 5, 5, 5, 5, 5, 5, 5],
 'config_dir': './config',
 'data_dir': '/home/b306/fanzhaowei/CornerNet-master/data',
 'data_rng': <mtrand.RandomState object at 0x7f4cbfa899d8>,
 'dataset': 'MSCOCO',
 'decay_rate': 10,
 'display': 5,
 'learning_rate': 0.00025,
 'max_iter': 500000,
 'nnet_rng': <mtrand.RandomState object at 0x7f4cbfa89a20>,
 'opt_algo': 'adam',
 'prefetch_size': 5,
 'pretrain': None,
 'result_dir': './results',
 'sampling_function': 'kp_detection',
 'snapshot': 5000,
 'snapshot_name': 'CornerNet',
 'stepsize': 450000,
 'test_split': 'testdev',
 'train_split': 'trainval',
 'val_iter': 100,
 'val_split': 'minival',
 'weight_decay': False,
 'weight_decay_rate': 1e-05,
 'weight_decay_type': 'l2'}
db config...
{'ae_threshold': 0.5,
 'border': 128,
 'categories': 80,
 'data_aug': True,
 'gaussian_bump': True,
 'gaussian_iou': 0.7,
 'gaussian_radius': -1,
 'input_size': [511, 511],
 'lighting': True,
 'max_per_image': 100,
 'merge_bbox': False,
 'nms_algorithm': 'exp_soft_nms',
 'nms_kernel': 3,
 'nms_threshold': 0.5,
 'output_sizes': [[128, 128]],
 'rand_color': True,
 'rand_crop': True,
 'rand_pushes': False,
 'rand_samples': False,
 'rand_scale_max': 1.4,
 'rand_scale_min': 0.6,
 'rand_scale_step': 0.1,
 'rand_scales': array([0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3]),
 'special_crop': False,
 'test_scales': [1],
 'top_k': 100,
 'weight_exp': 8}
loading parameters at iteration: 500000
building neural network...
module_file: models.CornerNet
total parameters: 201035212
loading parameters...
loading model from ./cache/nnet/CornerNet/CornerNet_500000.pkl
locating kps:   0%|                                   | 0/40504 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 99, in <module>
    test(testing_db, args.split, args.testiter, args.debug, args.suffix)
  File "test.py", line 61, in test
    testing(db, nnet, result_dir, debug=debug)
  File "/home/b306/fanzhaowei/CornerNet-master/test/coco.py", line 206, in testing
    return globals()[system_configs.sampling_function](db, nnet, result_dir, debug=debug)
  File "/home/b306/fanzhaowei/CornerNet-master/test/coco.py", line 77, in kp_detection
    height, width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'


@heilaw @Iric2018 could you please tell me how to solve it? I have put the pictures in correct folder

**Comment by zhaowujie** [comment]
需要三个文件夹和三个json文件
![image](https://user-images.githubusercontent.com/34273042/49069396-23701700-f264-11e8-9df2-b23a874feae3.png)
![image](https://user-images.githubusercontent.com/34273042/49069449-3c78c800-f264-11e8-850c-edd1dc899ebc.png)
把这些弄好了就不报错了 @Iric2018

**Comment by maggiequan** [comment]
> I just replace the images with my own images of the file testdev2017，then run the python test.py CornerNet --testiter 500000 --split testing，and the error come up as follow：
> cfg_file: ./config/CornerNet.json
> loading all datasets...
> split: testdev
> loading from cache file: ./cache/coco_testdev2017.pkl
> No cache file found...
> loading annotations into memory...
> Done (t=0.05s)
> creating index...
> index created!
> 20288it [00:08, 2410.16it/s]
> loading annotations into memory...
> Done (t=0.05s)
> creating index...
> index created!
> system config...
> {'batch_size': 49,
> 'cache_dir': './cache',
> 'chunk_sizes': [4, 5, 5, 5, 5, 5, 5, 5, 5, 5],
> 'config_dir': './config',
> 'data_dir': './data',
> 'data_rng': <mtrand.RandomState object at 0x7f847ac04438>,
> 'dataset': 'MSCOCO',
> 'decay_rate': 10,
> 'display': 5,
> 'learning_rate': 0.00025,
> 'max_iter': 500000,
> 'nnet_rng': <mtrand.RandomState object at 0x7f847ac04480>,
> 'opt_algo': 'adam',
> 'prefetch_size': 5,
> 'pretrain': None,
> 'result_dir': './results',
> 'sampling_function': 'kp_detection',
> 'snapshot': 5000,
> 'snapshot_name': 'CornerNet',
> 'stepsize': 450000,
> 'test_split': 'testdev',
> 'train_split': 'trainval',
> 'val_iter': 100,
> 'val_split': 'minival',
> 'weight_decay': False,
> 'weight_decay_rate': 1e-05,
> 'weight_decay_type': 'l2'}
> db config...
> {'ae_threshold': 0.5,
> 'border': 128,
> 'categories': 80,
> 'data_aug': True,
> 'gaussian_bump': True,
> 'gaussian_iou': 0.7,
> 'gaussian_radius': -1,
> 'input_size': [511, 511],
> 'lighting': True,
> 'max_per_image': 100,
> 'merge_bbox': False,
> 'nms_algorithm': 'exp_soft_nms',
> 'nms_kernel': 3,
> 'nms_threshold': 0.5,
> 'output_sizes': [[128, 128]],
> 'rand_color': True,
> 'rand_crop': True,
> 'rand_pushes': False,
> 'rand_samples': False,
> 'rand_scale_max': 1.4,
> 'rand_scale_min': 0.6,
> 'rand_scale_step': 0.1,
> 'rand_scales': array([0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3]),
> 'special_crop': False,
> 'test_scales': [1],
> 'top_k': 100,
> 'weight_exp': 8}
> loading parameters at iteration: 500000
> building neural network...
> module_file: models.CornerNet
> total parameters: 201035212
> loading parameters...
> loading model from ./cache/nnet/CornerNet/CornerNet_500000.pkl
> locating kps: 0%| | 1/20288 [00:00<2:44:31, 2.06it/s]
> Traceback (most recent call last):
> File "test.py", line 99, in 
> test(testing_db, args.split, args.testiter, args.debug, args.suffix)
> File "test.py", line 61, in test
> testing(db, nnet, result_dir, debug=debug)
> File "/home/dc2-user/CornerNet-master/test/coco.py", line 204, in testing
> return globals()[system_configs.sampling_function](db, nnet, result_dir, debug=debug)
> File "/home/dc2-user/CornerNet-master/test/coco.py", line 77, in kp_detection
> height, width = image.shape[0:2]
> AttributeError: 'NoneType' object has no attribute 'shape'
> What should I do？Thanks。

can you tell me how to do it? i meet the same question.how to change the path in coco.py, can you share it?

**Comment by Iric2018** [comment]
Do you have download the training/validation split and put them into the corresponding directory as it was said in readme.md?

**Comment by Iric2018** [comment]
@maggiequan @fanzhaowei Do you have download the training/validation split and put them into the corresponding directory as it was said in readme.md?

**Comment by maggiequan** [comment]
@Iric2018 
![image](https://user-images.githubusercontent.com/24451275/49143703-8fbb4b00-f336-11e8-8a3a-92ffa8917012.png)
![image](https://user-images.githubusercontent.com/24451275/49143759-ad88b000-f336-11e8-9bd6-58761439d140.png)
data/coco/annotations downloaded from the given link, i put my pictures in data/coco/images/testdev2017 just like the picture above.

**Comment by maggiequan** [comment]
heilaw say: change the coco.py？发自我的华为手机-------- 原始邮件 --------主题：Re: [princeton-vl/CornerNet] How can I predict the objects in my own pictures？ (#17)发件人：Iric2018 收件人：princeton-vl/CornerNet 抄送：maggiequan ,Mention @maggiequan @fanzhaowei Do you have download the training/validation split and put them into the corresponding directory as it was said in readme.md?

**Comment by maggiequan** [comment]
@zhaowujie hello,三个文件夹是自己新建的，三个json是从网上下载下来的只不过testdev文件夹里放的是自己的图片，其他什么都没有修改，这肯定是有问题的。但是@heilaw说修改db /coco.py，但是我不知道如何修改。
