### ISSUE TITLE
RuntimeError: cuda runtime error (10) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/THCGeneral.cpp:70

### ISSUE THREAD

**Issue by lianbobo** [umich-vl/CornerNet#25]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/THCGeneral.cpp line=70 error=10 : invalid device ordinal
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/lianbo/anaconda3/envs/Pytorch/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/lianbo/anaconda3/envs/Pytorch/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 55, in pin_memory
    data["xs"] = [x.pin_memory() for x in data["xs"]]
  File "train.py", line 55, in <listcomp>
    data["xs"] = [x.pin_memory() for x in data["xs"]]

**Comment by heilaw** [comment]
#15
