### ISSUE TITLE
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by XzlXcc** [umich-vl/CornerNet#93]
I got the following error when training: 
`training start...
  0%|                                                | 0/500000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "train.py", line 137, in train
    training_loss = nnet.train(**training)
  File "/media/image522/2/Xie/CornerNet/nnet/py_factory.py", line 81, in train
    loss = self.network(xs, ys)
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/image522/2/Xie/CornerNet/models/py_utils/data_parallel.py", line 68, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/image522/2/Xie/CornerNet/nnet/py_factory.py", line 19, in forward
    preds = self.model(*xs, **kwargs)
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/image522/2/Xie/CornerNet/nnet/py_factory.py", line 31, in forward
    return self.module(*xs, **kwargs)
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/image522/2/Xie/CornerNet/models/py_utils/kp.py", line 253, in forward
    return self._train(*xs, **kwargs)
  File "/media/image522/2/Xie/CornerNet/models/py_utils/kp.py", line 171, in _train
    inter = self.pre(image)
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/image522/2/Xie/CornerNet/models/py_utils/utils.py", line 14, in forward
    conv = self.conv(x)
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/image522/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_MAPPING_ERROR
`
Is it related to the mismatch of my pytorch version and cuda version(my cuda is 10.0)?

**Comment by ucasfhx** [comment]
I met the same issue, have you solved it?

**Comment by GeorgeP24** [comment]
I have some problem 。
I'm going to train in cuda 8.0 and cuda 10.1。

**Comment by UmarSpa** [comment]
Any update on this ? Anyone able to solve this problem ?

**Comment by guohaoyuan** [comment]
Anyone able to solve this problem ?

**Comment by chordxu** [comment]
I met the same problem, do you solve it?
